<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { pipelinesApi } from '@/api/pipelines';
import { useToastStore } from '@/stores/toast';
import { parseApiError } from '@/utils/errors';
import FormField from '@/components/FormField.vue';
import LoadingBlock from '@/components/LoadingBlock.vue';

const props=defineProps({id:{type:String,default:null}}); const router=useRouter(); const toast=useToastStore(); const isEdit=computed(()=>!!props.id); const loading=ref(true); const saving=ref(false); const errors=ref({}); const stages=ref([]);
const form=reactive({name:'',description:'',is_default:false,is_active:true}); const stage=reactive({name:'',color:'secondary',probability:0,is_won:false,is_lost:false}); const editingStage=ref(null);
async function load(){ if(!isEdit.value){loading.value=false;return;} try{const p=await pipelinesApi.get(props.id); Object.assign(form,{name:p.name,description:p.description||'',is_default:p.is_default,is_active:p.is_active}); stages.value=p.stages||[];}catch(e){toast.error(parseApiError(e).message);router.replace({name:'pipelines.index'});}finally{loading.value=false;} }
async function save(){saving.value=true;errors.value={};try{const p=isEdit.value?await pipelinesApi.update(props.id,form):await pipelinesApi.create(form);toast.success(isEdit.value?'Pipeline updated.':'Pipeline created.');if(!isEdit.value) router.replace({name:'pipelines.edit',params:{id:p.id}}); else await load();}catch(e){const x=parseApiError(e);errors.value=x.fields;toast.error(x.message);}finally{saving.value=false;}}
async function saveStage(){if(!stage.name.trim())return;try{if(editingStage.value){const updated=await pipelinesApi.updateStage(props.id,editingStage.value.id,{...stage});stages.value=stages.value.map(s=>s.id===updated.id?updated:s);editingStage.value=null;}else{const created=await pipelinesApi.createStage(props.id,{...stage,position:stages.value.length+1});stages.value.push(created);} Object.assign(stage,{name:'',color:'secondary',probability:0,is_won:false,is_lost:false});}catch(e){toast.error(parseApiError(e).message);}}
function editStage(s){editingStage.value=s;Object.assign(stage,{name:s.name,color:s.color,probability:s.probability,is_won:s.is_won,is_lost:s.is_lost});}
function cancelStage(){editingStage.value=null;Object.assign(stage,{name:'',color:'secondary',probability:0,is_won:false,is_lost:false});}
async function removeStage(s){try{await pipelinesApi.removeStage(props.id,s.id);stages.value=stages.value.filter(x=>x.id!==s.id);}catch(e){toast.error(parseApiError(e).message);}}
async function move(index,direction){const next=index+direction;if(next<0||next>=stages.value.length)return;const copy=[...stages.value];[copy[index],copy[next]]=[copy[next],copy[index]];const payload=copy.map((s,i)=>({id:s.id,position:i+1}));try{await pipelinesApi.reorderStages(props.id,payload);stages.value=copy.map((s,i)=>({...s,position:i+1}));}catch(e){toast.error(parseApiError(e).message);}}
onMounted(load);
</script>
<template>
<h1 class="h3 mb-4">{{isEdit?'Edit pipeline':'New pipeline'}}</h1><LoadingBlock v-if="loading" />
<template v-else><div class="card mb-4"><div class="card-body"><form class="row g-3" @submit.prevent="save"><FormField class="col-12" label="Name" required :error="errors.name"><input v-model="form.name" class="form-control" :class="{'is-invalid':errors.name}" required /></FormField><FormField class="col-12" label="Description" :error="errors.description"><textarea v-model="form.description" class="form-control" rows="3"></textarea></FormField><div class="col-md-6"><div class="form-check"><input id="active" v-model="form.is_active" class="form-check-input" type="checkbox"><label class="form-check-label" for="active">Active</label></div></div><div class="col-md-6"><div class="form-check"><input id="default" v-model="form.is_default" class="form-check-input" type="checkbox"><label class="form-check-label" for="default">Default pipeline</label></div></div><div class="col-12"><button class="btn btn-primary" :disabled="saving">Save pipeline</button><RouterLink :to="{name:'pipelines.index'}" class="btn btn-outline-secondary ms-2">Cancel</RouterLink></div></form></div></div>
<div v-if="isEdit" class="card"><div class="card-header bg-white d-flex justify-content-between"><strong>Stages</strong><RouterLink :to="{name:'pipelines.board',params:{id:props.id}}" class="btn btn-sm btn-outline-secondary">Open board</RouterLink></div><div class="card-body">
<form class="row g-2 mb-4" @submit.prevent="saveStage"><div class="col-lg-4"><input v-model="stage.name" class="form-control" placeholder="Stage name" required></div><div class="col-lg-2"><select v-model="stage.color" class="form-select"><option v-for="c in ['secondary','info','primary','warning','success','danger']" :key="c" :value="c">{{c}}</option></select></div><div class="col-lg-2"><input v-model.number="stage.probability" type="number" min="0" max="100" class="form-control" placeholder="Probability"></div><div class="col-lg-2 form-check d-flex align-items-center ps-4"><input id="won" v-model="stage.is_won" type="checkbox" class="form-check-input"><label for="won" class="form-check-label ms-2">Won</label></div><div class="col-lg-2 form-check d-flex align-items-center ps-4"><input id="lost" v-model="stage.is_lost" type="checkbox" class="form-check-input"><label for="lost" class="form-check-label ms-2">Lost</label></div><div class="col-12"><button class="btn btn-outline-primary">{{editingStage?'Update stage':'Add stage'}}</button><button v-if="editingStage" type="button" class="btn btn-link" @click="cancelStage">Cancel</button></div></form>
<div v-for="(s,i) in stages" :key="s.id" class="border rounded p-3 mb-2 d-flex align-items-center justify-content-between"><div><strong>{{s.position}}. {{s.name}}</strong><span class="badge ms-2" :class="`text-bg-${s.color}`">{{s.probability}}%</span><span v-if="s.is_won" class="badge text-bg-success ms-1">Won</span><span v-if="s.is_lost" class="badge text-bg-danger ms-1">Lost</span><div class="small text-muted">{{s.deals_count??0}} deals</div></div><div><button class="btn btn-sm btn-outline-secondary" :disabled="i===0" @click="move(i,-1)">↑</button><button class="btn btn-sm btn-outline-secondary ms-1" :disabled="i===stages.length-1" @click="move(i,1)">↓</button><button class="btn btn-sm btn-outline-primary ms-1" @click="editStage(s)">Edit</button><button class="btn btn-sm btn-outline-danger ms-1" @click="removeStage(s)">Delete</button></div></div>
</div></div></template>
</template>
